blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/nayandas69/faceverify/tree/main/docs
    about: Check the documentation before opening an issue
  - name: Discussions
    url: https://github.com/nayandas69/faceverify/discussions
    about: Ask questions and discuss ideas
